name: LFS Auto Track E2E Test on Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 9
          run_install: false

      - name: Install Git LFS
        run: |
          sudo apt-get update
          sudo apt-get install git-lfs
          git lfs install

      - name: Install Dependencies
        run: |
          pnpm install

      - name: Run husky
        run: |
          pnpm husky

      - name: Build lib
        run: |
          pnpm build

      - name: Check ./lib
        run: |
          ls lib

      - name: Check ./bin
        run: |
          ls bin

      - name: Run unit tests
        run: |
          pnpm run test

      - name: Create E2E Test Files
        run: |
          truncate -s 1K small.txt
          truncate -s 2M large.txt
          truncate -s 50K small.jpg
          truncate -s 150K large.jpg
          git add .

      - name: Commit Files
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -m "Test lfs-auto-track functionality"

      - name: Verify LFS Tracking
        run: |
          # Check if large files are tracked by LFS
          echo "LFS tracked files:"
          git lfs ls-files

          # Verify large.txt is tracked
          if git lfs ls-files | grep -q "large.txt"; then
            echo "✅ large.txt is tracked by LFS as expected"
          else
            echo "❌ large.txt is NOT tracked by LFS"
            exit 1
          fi

          # Verify large.jpg is tracked
          if git lfs ls-files | grep -q "large.jpg"; then
            echo "✅ large.jpg is tracked by LFS as expected"
          else
            echo "❌ large.jpg is NOT tracked by LFS"
            exit 1
          fi

          # Check .gitattributes content
          echo "Git attributes content:"
          cat .gitattributes

          # Verify .gitattributes contains proper LFS patterns
          if grep -q "large.jpg filter=lfs" .gitattributes && grep -q "large.txt filter=lfs" .gitattributes; then
            echo "✅ .gitattributes contains correct LFS patterns"
          else
            echo "❌ .gitattributes does not contain expected LFS patterns"
            exit 1
          fi
