name: LFS Auto Track E2E Test on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 9
          run_install: false

      - name: Install Git LFS
        run: |
          choco install git-lfs
          git lfs install

      - name: Install Dependencies
        run: |
          pnpm install

      - name: Run husky
        run: |
          pnpm husky

      - name: Build lib
        run: |
          pnpm run build

      - name: Create E2E Test Files
        run: |
          fsutil file createnew small.txt 1024
          fsutil file createnew large.txt 2097152
          fsutil file createnew small.jpg 51200
          fsutil file createnew large.jpg 153600
          git add .

      - name: Run unit tests
        run: |
          pnpm run test

      - name: Commit Files
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -m "Test lfs-auto-track functionality"
          echo Content of .gitattributes:
          type .gitattributes

      - name: Verify LFS Tracking
        shell: cmd
        run: |
          @echo off

          :: Display tracked LFS files
          echo LFS tracked files:
          type .gitattributes

          :: Check if large.txt is tracked by LFS
          type .gitattributes | findstr "large.txt" > nul
          if %ERRORLEVEL% == 0 (
            echo ✅ large.txt is tracked by LFS as expected
          ) else (
            echo ❌ large.txt is NOT tracked by LFS
            exit /b 1
          )

          :: Check if large.jpg is tracked by LFS
          type .gitattributes | findstr "large.jpg" > nul
          if %ERRORLEVEL% == 0 (
            echo ✅ large.jpg is tracked by LFS as expected
          ) else (
            echo ❌ large.jpg is NOT tracked by LFS
            exit /b 1
          )

          :: Display .gitattributes content
          echo Git attributes content:
          type .gitattributes
